<a href="https://colab.research.google.com/github/Fenix-LAB/App_Detector_PlacasVehiculares/blob/master/Test_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import cv2
import matplotlib.pyplot as plt

df=pd.read_csv("/content/drive/MyDrive/Red_Neuronal/Radiografias_Data_Set.csv")

In [ ]:
df.head(5)

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y]
0,00000001_000.png,Cardiomegaly,0,1,57,M,PA,2682,2749,0.143,0.143
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,0.143
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,0.168
3,00000002_000.png,No Finding,0,2,80,M,PA,2500,2048,0.171,0.171
4,00000003_001.png,Hernia,0,3,74,F,PA,2500,2048,0.168,0.168

In [ ]:
df["Finding Labels"].value_counts().to_frame()

                                                    Finding Labels
No Finding                                                   60361
Infiltration                                                  9547
Atelectasis                                                   4215
Effusion                                                      3955
Nodule                                                        2705
...                                                            ...
Atelectasis|Consolidation|Edema|Effusion|Infilt...               1
Atelectasis|Consolidation|Effusion|Emphysema|Ma...               1
Cardiomegaly|Effusion|Pleural_Thickening|Pneumo...               1
Edema|Infiltration|Pneumothorax                                  1
Atelectasis|Consolidation|Mass|Pleural_Thickeni...               1

[836 rows x 1 columns]

In [75]:
df_img=df.iloc[0:100,0:2]
Imagenes=[]

for name in df.iloc[0:100,0]:
  #print(name)
  dir = '/content/drive/MyDrive/Red_Neuronal/100_Images/image'
  dire = dir.replace("image",name)
  #print(dire)
  ima = cv2.imread(dire) 
  Imagenes.append(ima)

In [55]:
df_test=df.iloc[100:126,0:2]
Test=[]

for name in df.iloc[100:126,0]:
  #print(name)
  dir = '/content/drive/MyDrive/Red_Neuronal/20_Images/image'
  dire = dir.replace("image",name)
  #print(dire)
  ima = cv2.imread(dire) 
  Test.append(ima)

In [76]:
df_img['Image'] = Imagenes

In [57]:
df_test['Image'] = Test

In [77]:
df_img.head(3)

,Image Index,Finding Labels,Image
0,00000001_000.png,Cardiomegaly,"[[[202, 202, 202], [199, 199, 199], [195, 195,..."
1,00000001_001.png,Cardiomegaly|Emphysema,"[[[208, 208, 208], [205, 205, 205], [206, 206,..."
2,00000001_002.png,Cardiomegaly|Effusion,"[[[7, 7, 7], [10, 10, 10], [9, 9, 9], [8, 8, 8..."

In [ ]:
df_img.tail(3)

,Image Index,Finding Labels,Image
97,00000021_001.png,Infiltration,"[[[78, 78, 78], [120, 120, 120], [111, 111, 11..."
98,00000022_000.png,No Finding,"[[[251, 251, 251], [251, 251, 251], [253, 253,..."
99,00000022_001.png,Fibrosis,"[[[5, 5, 5], [10, 10, 10], [9, 9, 9], [9, 9, 9..."

In [60]:
df_test.head(3)

,Image Index,Finding Labels,Image
100,00000023_000.png,No Finding,"[[[4, 4, 4], [12, 12, 12], [11, 11, 11], [8, 8..."
101,00000023_001.png,No Finding,"[[[10, 10, 10], [17, 17, 17], [16, 16, 16], [1..."
102,00000023_002.png,Effusion|Infiltration,"[[[4, 4, 4], [7, 7, 7], [7, 7, 7], [6, 6, 6], ..."

In [ ]:
from tensorflow import keras

model = keras.Sequential()
    #keras.layers.Flatten(input_shape=(1024, 1024)),
model.add(keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(1024, 1024, 3)))
model.add(keras.layers.Dense(10000, activation='relu'))
model.add(keras.layers.Dense(8))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 1022, 1022, 32)    896

 dense (Dense)               (None, 1022, 1022, 10000  330000
                             )

 dense_1 (Dense)             (None, 1022, 1022, 8)     80008

=================================================================
Total params: 410,904
Trainable params: 410,904
Non-trainable params: 0
_________________________________________________________________

In [80]:
df_test.iloc[:,2]

100    [[[4, 4, 4], [12, 12, 12], [11, 11, 11], [8, 8...
101    [[[10, 10, 10], [17, 17, 17], [16, 16, 16], [1...
102    [[[4, 4, 4], [7, 7, 7], [7, 7, 7], [6, 6, 6], ...
103    [[[3, 3, 3], [7, 7, 7], [7, 7, 7], [7, 7, 7], ...
104    [[[45, 45, 45], [75, 75, 75], [68, 68, 68], [6...
105    [[[13, 13, 13], [25, 25, 25], [23, 23, 23], [2...
106    [[[200, 200, 200], [183, 183, 183], [177, 177,...
107    [[[1, 1, 1], [0, 0, 0], [0, 0, 0], [0, 0, 0], ...
108    [[[241, 241, 241], [242, 242, 242], [239, 239,...
109    [[[5, 5, 5], [10, 10, 10], [10, 10, 10], [10, ...
110    [[[19, 19, 19], [19, 19, 19], [19, 19, 19], [1...
111    [[[44, 44, 44], [37, 37, 37], [31, 31, 31], [2...
112    [[[74, 74, 74], [63, 63, 63], [54, 54, 54], [4...
113    [[[151, 151, 151], [147, 147, 147], [140, 140,...
114    [[[4, 4, 4], [5, 5, 5], [5, 5, 5], [5, 5, 5], ...
115    [[[3, 3, 3], [4, 4, 4], [4, 4, 4], [4, 4, 4], ...
116    [[[3, 3, 3], [6, 6, 6], [5, 5, 5], [4, 4, 4], ...
117    [[[4, 4, 4], [7, 7, 7], [6, 6, 6], [6, 6, 6], ...
118    [[[4, 4, 4], [7, 7, 7], [7, 7, 7], [7, 7, 7], ...
119    [[[2, 2, 2], [4, 4, 4], [4, 4, 4], [4, 4, 4], ...
120    [[[4, 4, 4], [6, 6, 6], [6, 6, 6], [6, 6, 6], ...
121    [[[2, 2, 2], [5, 5, 5], [4, 4, 4], [4, 4, 4], ...
122    [[[2, 2, 2], [4, 4, 4], [3, 3, 3], [3, 3, 3], ...
123    [[[1, 1, 1], [2, 2, 2], [3, 3, 3], [2, 2, 2], ...
124    [[[1, 1, 1], [2, 2, 2], [3, 3, 3], [2, 2, 2], ...
125                                                 None
Name: Image, dtype: object

In [83]:
labels_img=df_img['Finding Labels'].to_list()
labels_test=df_test['Finding Labels'].to_list()

In [85]:
model.compile(optimizer='adam',
              loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(Imagenes, labels_img, epochs=10, 
                    validation_data=(Test, labels_test))

ValueError: ignored